apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: demo-workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

# Steps
# - Test (python)
# - parallel scans
#   - Synk
#   - Sonarqube
# - package (python)
# - Docker build
# - Snyk container scan
# - Docker push
# - Post (always) get metrics collection and send emails

jobs:
  test:
    outputs:
      CODE_COVERAGE: ${{ steps.unit-tests.outputs.CODE_COVERAGE }}
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
      - name: Run unit tests
        id: unit-tests
        uses: docker://python:3.14-slim
        kind: test
        run: |
          pip install -r requirements-dev.txt
          pytest --junitxml=test-results.xml --cov=app --cov-report=markdown --cov-report=term
          cat coverage.md > "$CLOUDBEES_OUTPUTS/CODE_COVERAGE"

      - uses: cloudbees-io/publish-test-results@v2
        with:
          test-type: JUNIT
          results-path: ${{ cloudbees.workspace }}/test-results.xml

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Test code coverage

            ${{ steps.unit-tests.outputs.CODE_COVERAGE }}
          format: MARKDOWN

  snyk:
    needs:
      - test
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
      - name: Scan with Snyk SAST
        id: snyk-sast
        uses: https://github.com/cloudbees-io/snyk-sast-scan-code@v1
        with:
          orgname: ${{ vars.SNYK_ORG }}
          token: ${{ secrets.SNYK_SECRET }}
          language: "LANGUAGE_PYTHON"
      - name: Scan with Snyk SCA
        id: snyk-sca
        uses: https://github.com/cloudbees-io/snyk-sca-scan-dependency@v1
        with:
          orgname: ${{ vars.SNYK_ORG }}
          token: ${{ secrets.SNYK_SECRET }}
          language: "LANGUAGE_PYTHON"

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Snyk SAST results

            Critical count: ${{steps.snyk-sast.outputs.critical-count}}
            Very high count: ${{steps.snyk-sast.outputs.very-high-count}}
            High count: ${{steps.snyk-sast.outputs.high-count}}
            Medium count: ${{steps.snyk-sast.outputs.medium-count}}
            Low count: ${{steps.snyk-sast.outputs.low-count}}


            ## Snyk SCA results

            Critical count: ${{steps.snyk-sca.outputs.critical-count}}
            Very high count: ${{steps.snyk-sca.outputs.very-high-count}}
            High count: ${{steps.snyk-sca.outputs.high-count}}
            Medium count: ${{steps.snyk-sca.outputs.medium-count}}
            Low count: ${{steps.snyk-sca.outputs.low-count}}

  sonarqube:
    needs:
      - test
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
      - name: Scan with SonarQube
        id: sonar-scan
        uses: cloudbees-io/sonarqube-plugin@v1
        with:
          server-url: ${{ vars.SONAR_URL }}
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Sonar scan results

            Critical count: ${{steps.sonar-scan.outputs.critical-count}}
            Very high count: ${{steps.sonar-scan.outputs.very-high-count}}
            High count: ${{steps.sonar-scan.outputs.high-count}}
            Medium count: ${{steps.sonar-scan.outputs.medium-count}}
            Low count: ${{steps.sonar-scan.outputs.low-count}}
